version: "3.8"

services:
  wordpress:
    build: .
    restart: always
    ports:
      - 1234:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wp_db
    volumes:
      - type: bind
        source: /Users/samseay/Code/automattic/woocommerce
        target: /var/www/html/wp-content/plugins/woocommerce
      - type: bind
        source: /Users/samseay/Code/automattic/woocommerce-admin
        target: /var/www/html/wp-content/plugins/woocommerce-admin
      - type: volume
        source: wp_data
        target: /var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7.29
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wp_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql

  wordpress-cli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    user: xfs
    command: >
      /bin/sh -c '
      sleep 10;
      wp core install --path="/var/www/html" --url="http://docker.for.mac.localhost:1234" --title="WooCommerce Dev" --admin_user=admin --admin_password=password --admin_email=admin@example.com
      '
    volumes:
      - wp_data:/var/www/html

volumes:
  db:
  wp_data:
