version: "3.8"

services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 1234:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wp_db
    volumes:
      - type: bind
        source: "${PLUGIN_DEV_DIRECTORY}"
        target: /var/www/html/wp-content/plugins
      - type: volume
        source: wp_data
        target: /var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7.29
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wp_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql

  wordpress-cli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    user: xfs
    command: >
      /bin/sh -c '
      sleep 20;
      wp core install --path="/var/www/html" --url="http://localhost:1234" --title="WooCommerce Dev" --admin_user=admin --admin_password=password --admin_email=admin@example.com;
      wp plugin install jetpack;      
      wp config set JETPACK_AUTOLOAD_DEV true --raw --debug=bootstrap;      
      wp config set WP_DEBUG true --raw --debug=bootstrap;
      wp config set SCRIPT_DEBUG true --raw --debug=bootstrap;
      wp config set WP_DEBUG_LOG true --raw --debug=bootstrap;
      wp config set WP_DEBUG_DISPLAY false --raw --debug=bootstrap;
      '
    volumes:
      - wp_data:/var/www/html

volumes:
  db:
  wp_data:
